<?php $_helper = Mage::helper('productvisibility') ?>
<script type="text/javascript">
<!--
    function fireEvent(obj,evt){
    
        var fireOnThis = obj;
        if( document.createEvent ) {
            var evObj = document.createEvent('MouseEvents');
            evObj.initEvent( evt, true, false );
            fireOnThis.dispatchEvent(evObj);
        } else if( document.createEventObject ) {
            fireOnThis.fireEvent('on'+evt);
        }
    }
//-->
</script>
<table class="product_visibility_checkpoints">
    <?php foreach ($this->getCheckpoints() as $checkpoint): ?>
        <tr>
            <th><?php echo $_helper->__($checkpoint->getName()) ?></th>
            <td class="visibility_<?php echo $checkpoint->isVisible() ? 'on' : 'off' ?>">
                <?php echo $checkpoint->isVisible() ? '+' : '-' ?>
            </td>
            <td class="<?php echo $checkpoint->isVisible() ? 'details' : 'howto' ?>">
                <?php if ($checkpoint->isinvisible()): ?>
                    <ul>
                        <?php foreach ($this->getHowto($checkpoint->getName()) as $howto): ?>
                            <li><?php echo $_helper->__($howto) ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <?php echo $checkpoint->getDetails() ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>